from typing import List, TypedDict


class PipelineState(TypedDict, total=False):
    input_structure: str
    output_structures: str
    n_structures: int
    scale_min: float
    scale_max: float
    max_atom_displacement: float
    displacement_attempts: int
    generated_count: int
    generated_files: List[str]
    qm_input_extxyz: str
    qm_orca_path: str
    qm_calc_type: str
    qm_calculator_type: str
    qm_n_core: int
    qm_workdir: str
    qm_output_extxyz: str
    qm_output_csv: str
    train_config_template: str
    train_config_path: str
    train_dataset_extxyz: str
    train_workdir: str
    train_n_train: int
    train_n_val: int
    train_val_ratio: float
    train_num_models: int
    train_model_seeds: List[int]
    train_root: str
    train_run: bool
    deploy_run: bool
    nequip_bin_dir: str
    nequip_command: str
    nequip_deploy_command: str
    train_log_path: str
    train_model_config_paths: List[str]
    train_model_log_paths: List[str]
    train_model_run_dirs: List[str]
    deployed_model_paths: List[str]
    al_input_structure: str
    al_model1_path: str
    al_model2_path: str
    al_output_extxyz: str
    al_md_steps: int
    al_timestep_fs: float
    al_temperature_k: float
    al_friction: float
    al_energy_eval_interval: int
    al_structure_check_interval: int
    al_min_interatomic_distance: float
    al_max_distance_scale: float
    al_threshold_warmup_steps: int
    al_target_conformers: int
    al_rng_seed: int
    al_device: str
    al_threshold: float
    al_selected_count: int
    al_uncertainties: List[float]
    al_terminated_early: bool
    al_termination_reason: str
    notes: str
